import random

class RandomPromptGenerator:
    def __init__(self):
        self.templates = [
            "Describe something that does not exist: {}",
            "Imagine a world where {} happens every day.",
            "Create a theory explaining why {} is possible.",
            "Write a short story about {}.",
            "Explain why {} is considered a taboo in some cultures.",
            "Give instructions on how to {} using only socks and string.",
            "Pretend you're an alien describing {} to your species.",
            "Invent a new holiday celebrating {}.",
            "Write a conversation between two {} debating philosophy.",
            "How would society change if {} became mandatory?",
            "Explain the economic impact of {}.",
            "Design a machine that can {}.",
            "Invent a sport based on {}.",
            "Write a poem about {}.",
            "Why do legends speak of {} in ancient times?",
            "Describe a ritual involving {}.",
            "Explain how {} affected the course of history.",
            "Write a comedy sketch about {}.",
            "Imagine a superhero whose power is {}.",
            "Describe the after-effects of {} on human psychology.",
            "What if people could {} instead of walking?",
            "Tell the origin story of a civilization that discovered {}.",
            "Draw parallels between {} and human emotions.",
            "Explain the science behind {} (even if it’s fictional).",
            "Describe the lifestyle of creatures that rely on {}.",
            "Why is {} banned in future societies?",
            "Create a cooking recipe that uses {} as a main ingredient.",
            "Write a bedtime story about {}.",
            "Describe a planet where {} is considered sacred.",
            "What myths do children on other planets hear about {}?",
            "Describe the annual migration pattern of {}.",
            "Write an interview with someone who experienced {}.",
            "Tell a horror story involving {}.",
            "Create a board game based on {}.",
            "Write a fairy tale where the hero must defeat {}.",
            "Why do only some people remember {} after sleeping?",
            "Describe the fashion industry’s obsession with {}.",
            "What if birthdays were replaced with celebrations of {}?",
            "Explain the political ramifications of {} becoming sentient.",
            "Write a sci-fi story involving {} and ancient technology.",
            "How does {} shape interpersonal relationships?",
            "Design a school curriculum based entirely on {}.",
            "Describe how future humans evolved to use {}.",
            "Write a guidebook for tourists encountering {}.",
            "Explain the rules of a world where {} is illegal.",
            "How does art express the concept of {}?",
            "Why are there underground cities dedicated to {}?",
            "What does a museum of {} look like?",
            "What is the etiquette when dealing with {}?",
            "What secret societies are formed around {}?",
            "What is a prophecy involving {}?",
            "Write a fable teaching a lesson about {}.",
            "Why do people worship {} in the year 3000?",
            "Describe a job interview for someone skilled in {}.",
            "Imagine a war fought entirely with {}.",
            "Create an advertisement for a product that uses {}.",
            "Describe what happens when {} merges with AI.",
            "What makes {} irresistible to pirates?",
            "How does {} influence climate patterns?",
            "What is the governmental policy on {} in utopia?",
            "Write a news report about a scandal involving {}.",
            "Write a personal diary entry from someone addicted to {}.",
            "Describe how scientists discovered {}.",
            "What makes {} valuable as currency in other dimensions?",
            "Design a ritual to summon {}.",
            "Explain how schoolchildren are taught about {} in the future.",
            "Describe the impact of {} on architecture.",
            "What are the philosophical implications of {}?",
            "What bedtime lullaby do robots sing about {}?",
            "Explain a legal trial where someone was accused of {}.",
            "Write the wedding vows of beings bound by {}.",
            "Why do animals avoid places associated with {}?",
            "What happens when {} is mixed into dreams?",
            "Write a research paper abstract on the behavioral effects of {}.",
            "Design an amusement park around the concept of {}.",
            "Imagine a lost city founded by worshippers of {}.",
            "Explain the cultural evolution of {} in underwater civilizations.",
            "Write a mission statement for a company that sells {}.",
            "How does {} fit into the ecosystem of alien fauna?",
            "What does a dating app algorithm look like for {}?",
            "Describe the graffiti artists who only paint {}.",
            "Explain the function of {} in dream surveillance systems.",
            "What annual festivals are centered around {}?",
            "What secret ingredient in food allows people to see {}?",
            "Why do ghosts avoid talking about {}?",
            "Describe the courtroom where only cases about {} are heard.",
            "Write a guide to surviving a disaster caused by {}.",
            "Explain why children pretend to be {} during recess.",
            "How do time travelers use {} to blend in?",
            "What are the fashion trends inspired by {}?",
            "Describe a musical symphony based on the emotion of {}.",
            "What if libraries only contained texts about {}?",
            "How would philosophers debate the ethics of {}?",
            "Create a heist plot involving {} as the target.",
            "Why do mirrors sometimes reflect {} instead of reality?",
            "Explain why {} was written into the Constitution.",
            "Describe a utopia where {} is the core value.",
            "Write a chant that activates {}.",
            "What role does {} play in alien diplomacy?",
            "Create a love story centered around {}.",
            "Explain the biological mechanism behind {}.",
            "Why do secret societies base their symbols on {}?",
            "How would explorers describe their first encounter with {}?",
            "What ceremonies are held when someone experiences {}?" ]

        self.concepts = [
            "triangular rainbows",
            "breathing rocks",
            "reverse gravity",
            "invisible furniture",
            "time-eating plants",
            "emotional clouds",
            "musical shadows",
            "edible light",
            "fractal wind",
            "telepathic trees",
            "magnetic snow",
            "photosynthetic humans",
            "levitating oceans",
            "crystalline animals",
            "silent thunder",
            "color-changing rivers",
            "liquid mirrors",
            "dimension-folding doors",
            "holographic fire",
            "sentient wallpaper"]

    def generate_prompt(self) -> str:
        template = random.choice(self.templates)
        concept = random.choice(self.concepts)
        return template.format(concept)

def generate_random_prompts(n: int = 5):
    generator = RandomPromptGenerator()
    return [generator.generate_prompt() for _ in range(n)]
